# -*- coding: utf-8 -*-
"""CSCI 570 2026Sm_Final Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1L9xATvVsnK5AF_ym1ZgyR4UzVrobgRfQ
"""

"""Part B — builds the two strings (X, Y) to align from the input file.

Format: s0, then s's insertion indices (one per line), then t0, then t's indices.
Each step inserts a copy of the current string after the given 0-indexed spot,
doubling its length. j and k need not be equal.
"""


def _grow(base, indices):
    s = base
    for n in indices:
        s = s[:n + 1] + s + s[n + 1:]   # insert copy of current string after index n
    return s


def parse_and_generate(path):
    with open(path) as f:
        lines = [ln.strip() for ln in f if ln.strip()]

    i = 0
    s0 = lines[i]; i += 1

    # read s's indices until the first non-digit line, which is t0
    s_indices = []
    while i < len(lines) and lines[i].isdigit():
        s_indices.append(int(lines[i])); i += 1

    t0 = lines[i]; i += 1
    t_indices = [int(x) for x in lines[i:]]

    return _grow(s0, s_indices), _grow(t0, t_indices)